addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"     % "3.10.0")
addSbtPlugin("com.github.sbt"                    % "sbt-pgp"          % "2.2.1")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.2")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"          % "0.4.7")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.5.2")
