addSbtPlugin("org.xerial.sbt"                    % "sbt-sonatype"     % "3.9.17")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"          % "2.0.1")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.2")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"          % "0.4.0")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.5.0")
