pages = [{"l":"index.html","n":"SCROLL","t":"SCROLL","d":"","k":"static"},
{"l":"scroll/internal/compartment.html","n":"scroll.internal.compartment","t":"package scroll.internal.compartment","d":"scroll/internal/compartment","k":"package"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"CompartmentApi","t":"trait CompartmentApi","d":"scroll/internal/compartment/CompartmentApi","k":"trait"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"compartmentRelations","t":"val compartmentRelations: CompartmentRelationsApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"playerEquality","t":"val playerEquality: PlayerEqualityApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleConstraints","t":"val roleConstraints: RoleConstraintsApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleGraph","t":"val roleGraph: RoleGraphProxyApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleGroups","t":"val roleGroups: RoleGroupsApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"rolePlaying","t":"val rolePlaying: RolePlayingApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleQueries","t":"val roleQueries: RoleQueriesApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleRelationships","t":"val roleRelationships: RelationshipsApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/CompartmentApi.html","n":"roleRestrictions","t":"val roleRestrictions: RoleRestrictionsApi","d":"scroll/internal/compartment/CompartmentApi","k":"val"},
{"l":"scroll/internal/compartment/impl.html","n":"scroll.internal.compartment.impl","t":"package scroll.internal.compartment.impl","d":"scroll/internal/compartment/impl","k":"package"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"AbstractCompartment","t":"class AbstractCompartment() extends CompartmentApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"class"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"applyDispatchQuery","t":"def applyDispatchQuery(dispatchQuery: DispatchQuery, on: AnyRef): Seq[AnyRef]","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"compartmentRelations","t":"val compartmentRelations: CompartmentRelationsApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"either2TorException","t":"def either2TorException[T](either: Either[_, T]): T","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"newPlayer","t":"def newPlayer[W <: AnyRef : ClassTag](obj: W): IPlayer[W, _]","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"playerEquality","t":"val playerEquality: PlayerEqualityApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleConstraints","t":"val roleConstraints: RoleConstraintsApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleGraph","t":"val roleGraph: RoleGraphProxyApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleGroups","t":"val roleGroups: RoleGroupsApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"rolePlaying","t":"val rolePlaying: RolePlayingApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleQueries","t":"val roleQueries: RoleQueriesApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleRelationships","t":"val roleRelationships: RelationshipsApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment.html","n":"roleRestrictions","t":"val roleRestrictions: RoleRestrictionsApi","d":"scroll/internal/compartment/impl/AbstractCompartment","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"IPlayer","t":"class IPlayer[+W <: AnyRef, +T <: IPlayer[W, T]](val wrapped: W)(implicit evidence$2: ClassTag[W]) extends SCROLLDispatchable with Dynamic","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"class"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"<+>","t":"def <+>[R <: AnyRef : ClassTag](role: R): T","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"<->","t":"def <->(role: AnyRef): T","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"<=>","t":"def <=>[R <: AnyRef : ClassTag](role: R): W","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"drop","t":"def drop(role: AnyRef): T","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"facets","t":"def facets(): Seq[Value]","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"hasExtension","t":"def hasExtension[E <: AnyRef : ClassTag]: Boolean","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"hasFacets","t":"def hasFacets(f: Value*): Boolean","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"hasSomeFacet","t":"def hasSomeFacet(f: Value*): Boolean","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"isPlaying","t":"def isPlaying[R <: AnyRef : ClassTag]: Boolean","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"play","t":"def play[R <: AnyRef : ClassTag](role: R): T","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"player","t":"def player(using dispatchQuery: DispatchQuery): Either[TypeError, AnyRef]","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"playing","t":"def playing[R <: AnyRef : ClassTag](role: R): W","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"predecessors","t":"def predecessors(): Seq[AnyRef]","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"remove","t":"def remove(): Unit","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"roles","t":"def roles(): Seq[AnyRef]","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"transfer","t":"def transfer[R <: AnyRef : ClassTag](role: R): TransferToBuilder[R]","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"unary_+","t":"def unary_+: T","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer.html","n":"wrapped","t":"val wrapped: W","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer","k":"val"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer$TransferToBuilder.html","n":"TransferToBuilder","t":"class TransferToBuilder[R <: AnyRef](role: R)(implicit evidence$6: ClassTag[R])","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer$TransferToBuilder","k":"class"},
{"l":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer$TransferToBuilder.html","n":"to","t":"def to[P <: AnyRef : ClassTag](player: P): Unit","d":"scroll/internal/compartment/impl/AbstractCompartment$IPlayer$TransferToBuilder","k":"def"},
{"l":"scroll/internal/compartment/impl/Compartment.html","n":"Compartment","t":"trait Compartment extends AbstractCompartment","d":"scroll/internal/compartment/impl/Compartment","k":"trait"},
{"l":"scroll/internal/compartment/impl/Compartment.html","n":"Player","t":"def Player[W <: AnyRef : ClassTag](wrapped: W): Player[W]","d":"scroll/internal/compartment/impl/Compartment","k":"def"},
{"l":"scroll/internal/compartment/impl/Compartment$Player.html","n":"Player","t":"class Player[W <: AnyRef](val wrapped: W)(implicit evidence$2: ClassTag[W]) extends IPlayer[W, Player[W]] with SCROLLDynamic","d":"scroll/internal/compartment/impl/Compartment$Player","k":"class"},
{"l":"scroll/internal/compartment/impl/Compartment$Player.html","n":"hashCode","t":"def hashCode()(using dispatchQuery: DispatchQuery): Int","d":"scroll/internal/compartment/impl/Compartment$Player","k":"def"},
{"l":"scroll/internal/compartment/impl/Compartment$Player.html","n":"toString","t":"def toString()(using dispatchQuery: DispatchQuery): String","d":"scroll/internal/compartment/impl/Compartment$Player","k":"def"},
{"l":"scroll/internal/compartment/impl/Compartment$Player.html","n":"wrapped","t":"val wrapped: W","d":"scroll/internal/compartment/impl/Compartment$Player","k":"val"},
{"l":"scroll/internal/compartment/impl/MultiCompartment.html","n":"MultiCompartment","t":"trait MultiCompartment extends AbstractCompartment","d":"scroll/internal/compartment/impl/MultiCompartment","k":"trait"},
{"l":"scroll/internal/compartment/impl/MultiCompartment.html","n":"MultiPlayer","t":"def MultiPlayer[W <: AnyRef : ClassTag](wrapped: W): MultiPlayer[W]","d":"scroll/internal/compartment/impl/MultiCompartment","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment.html","n":"either2SeqTOrException","t":"def either2SeqTOrException[T](either: Either[_, Seq[Either[_, T]]]): Seq[T]","d":"scroll/internal/compartment/impl/MultiCompartment","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"MultiPlayer","t":"class MultiPlayer[W <: AnyRef](val wrapped: W)(implicit evidence$2: ClassTag[W]) extends IPlayer[W, MultiPlayer[W]]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"class"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"applyDynamic","t":"def applyDynamic[E](name: String)(args: Any*)(using dispatchQuery: DispatchQuery): Either[SCROLLError, Seq[Either[SCROLLError, E]]]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"applyDynamicNamed","t":"def applyDynamicNamed[E](name: String)(args: (String, Any)*)(using dispatchQuery: DispatchQuery): Either[SCROLLError, Seq[Either[SCROLLError, E]]]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"hashCode","t":"def hashCode()(using dispatchQuery: DispatchQuery): Seq[Int]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"selectDynamic","t":"def selectDynamic[E](name: String)(using dispatchQuery: DispatchQuery): Either[SCROLLError, Seq[Either[SCROLLError, E]]]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"toString","t":"def toString()(using dispatchQuery: DispatchQuery): Seq[String]","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"updateDynamic","t":"def updateDynamic(name: String)(value: Any)(using dispatchQuery: DispatchQuery): Unit","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"def"},
{"l":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer.html","n":"wrapped","t":"val wrapped: W","d":"scroll/internal/compartment/impl/MultiCompartment$MultiPlayer","k":"val"},
{"l":"scroll/internal/dispatch.html","n":"scroll.internal.dispatch","t":"package scroll.internal.dispatch","d":"scroll/internal/dispatch","k":"package"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"DispatchQuery","t":"object DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"object"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Bypassing","t":"def Bypassing(sel: Selector): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Conversion_Bypassing_DispatchQuery","t":"val Conversion_Bypassing_DispatchQuery: Conversion[Bypassing, DispatchQuery]","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Conversion_From_DispatchQuery","t":"val Conversion_From_DispatchQuery: Conversion[From, DispatchQuery]","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Conversion_Through_DispatchQuery","t":"val Conversion_Through_DispatchQuery: Conversion[Through, DispatchQuery]","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Conversion_To_DispatchQuery","t":"val Conversion_To_DispatchQuery: Conversion[To, DispatchQuery]","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"From","t":"def From(sel: Selector): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Selector","t":"type Selector = AnyRef => Boolean","d":"scroll/internal/dispatch/DispatchQuery$","k":"type"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"SelectorFunction","t":"type SelectorFunction = Seq[AnyRef] => Seq[AnyRef]","d":"scroll/internal/dispatch/DispatchQuery$","k":"type"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"Through","t":"def Through(sel: Selector): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"To","t":"def To(sel: Selector): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"anything","t":"val anything: Selector","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"apply","t":"def apply(): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery$","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"identity","t":"val identity: Boolean","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"nothing","t":"val nothing: Selector","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"reverse","t":"val reverse: PartialFunction[(AnyRef, AnyRef), Boolean]","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$.html","n":"swap","t":"val swap: Boolean","d":"scroll/internal/dispatch/DispatchQuery$","k":"val"},
{"l":"scroll/internal/dispatch/DispatchQuery$$Bypassing.html","n":"Bypassing","t":"class Bypassing(sel: Selector) extends SelectorFunction","d":"scroll/internal/dispatch/DispatchQuery$$Bypassing","k":"class"},
{"l":"scroll/internal/dispatch/DispatchQuery$$From.html","n":"From","t":"class From(sel: Selector) extends SelectorFunction","d":"scroll/internal/dispatch/DispatchQuery$$From","k":"class"},
{"l":"scroll/internal/dispatch/DispatchQuery$$Through.html","n":"Through","t":"class Through(sel: Selector) extends SelectorFunction","d":"scroll/internal/dispatch/DispatchQuery$$Through","k":"class"},
{"l":"scroll/internal/dispatch/DispatchQuery$$To.html","n":"To","t":"class To(sel: Selector) extends SelectorFunction","d":"scroll/internal/dispatch/DispatchQuery$$To","k":"class"},
{"l":"scroll/internal/dispatch/DispatchQuery.html","n":"DispatchQuery","t":"class DispatchQuery(from: From, to: To, through: Through, bypassing: Bypassing, var _sortedWith: Option[(AnyRef, AnyRef) => Boolean])","d":"scroll/internal/dispatch/DispatchQuery","k":"class"},
{"l":"scroll/internal/dispatch/DispatchQuery.html","n":"filter","t":"def filter(anys: Seq[AnyRef]): Seq[AnyRef]","d":"scroll/internal/dispatch/DispatchQuery","k":"def"},
{"l":"scroll/internal/dispatch/DispatchQuery.html","n":"sortedWith","t":"def sortedWith(f: PartialFunction[(AnyRef, AnyRef), Boolean]): DispatchQuery","d":"scroll/internal/dispatch/DispatchQuery","k":"def"},
{"l":"scroll/internal/dispatch/Dispatchable.html","n":"Dispatchable","t":"trait Dispatchable","d":"scroll/internal/dispatch/Dispatchable","k":"trait"},
{"l":"scroll/internal/dispatch/Dispatchable.html","n":"dispatch","t":"def dispatch[E](on: AnyRef, m: Method, args: Seq[Any]): Either[InvocationError, E]","d":"scroll/internal/dispatch/Dispatchable","k":"def"},
{"l":"scroll/internal/dispatch/SCROLLDynamic.html","n":"SCROLLDynamic","t":"trait SCROLLDynamic extends Dynamic","d":"scroll/internal/dispatch/SCROLLDynamic","k":"trait"},
{"l":"scroll/internal/dispatch/SCROLLDynamic.html","n":"applyDynamic","t":"def applyDynamic[E](name: String)(args: Any*)(using dispatchQuery: DispatchQuery): Either[SCROLLError, E]","d":"scroll/internal/dispatch/SCROLLDynamic","k":"def"},
{"l":"scroll/internal/dispatch/SCROLLDynamic.html","n":"applyDynamicNamed","t":"def applyDynamicNamed[E](name: String)(args: (String, Any)*)(using dispatchQuery: DispatchQuery): Either[SCROLLError, E]","d":"scroll/internal/dispatch/SCROLLDynamic","k":"def"},
{"l":"scroll/internal/dispatch/SCROLLDynamic.html","n":"selectDynamic","t":"def selectDynamic[E](name: String)(using dispatchQuery: DispatchQuery): Either[SCROLLError, E]","d":"scroll/internal/dispatch/SCROLLDynamic","k":"def"},
{"l":"scroll/internal/dispatch/SCROLLDynamic.html","n":"updateDynamic","t":"def updateDynamic(name: String)(value: Any)(using dispatchQuery: DispatchQuery): Unit","d":"scroll/internal/dispatch/SCROLLDynamic","k":"def"},
{"l":"scroll/internal/dispatch/impl.html","n":"scroll.internal.dispatch.impl","t":"package scroll.internal.dispatch.impl","d":"scroll/internal/dispatch/impl","k":"package"},
{"l":"scroll/internal/dispatch/impl/SCROLLDispatchable.html","n":"SCROLLDispatchable","t":"trait SCROLLDispatchable extends Dispatchable","d":"scroll/internal/dispatch/impl/SCROLLDispatchable","k":"trait"},
{"l":"scroll/internal/ecore.html","n":"scroll.internal.ecore","t":"package scroll.internal.ecore","d":"scroll/internal/ecore","k":"package"},
{"l":"scroll/internal/ecore/ECoreImporter.html","n":"ECoreImporter","t":"trait ECoreImporter","d":"scroll/internal/ecore/ECoreImporter","k":"trait"},
{"l":"scroll/internal/ecore/ECoreImporter.html","n":"loadModel","t":"def loadModel(path: String): Resource","d":"scroll/internal/ecore/ECoreImporter","k":"def"},
{"l":"scroll/internal/errors.html","n":"scroll.internal.errors","t":"package scroll.internal.errors","d":"scroll/internal/errors","k":"package"},
{"l":"scroll/internal/errors/SCROLLErrors$.html","n":"SCROLLErrors","t":"object SCROLLErrors","d":"scroll/internal/errors/SCROLLErrors$","k":"object"},
{"l":"scroll/internal/errors/SCROLLErrors$$IllegalRoleInvocationDispatch.html","n":"IllegalRoleInvocationDispatch","t":"class IllegalRoleInvocationDispatch(roleType: AnyRef, target: String, args: Seq[Any]) extends InvocationError","d":"scroll/internal/errors/SCROLLErrors$$IllegalRoleInvocationDispatch","k":"class"},
{"l":"scroll/internal/errors/SCROLLErrors$$InvocationError.html","n":"InvocationError","t":"trait InvocationError extends SCROLLError","d":"scroll/internal/errors/SCROLLErrors$$InvocationError","k":"trait"},
{"l":"scroll/internal/errors/SCROLLErrors$$RoleNotFound.html","n":"RoleNotFound","t":"class RoleNotFound(forCore: AnyRef, target: String, args: Seq[Any]) extends SCROLLError","d":"scroll/internal/errors/SCROLLErrors$$RoleNotFound","k":"class"},
{"l":"scroll/internal/errors/SCROLLErrors$$SCROLLError.html","n":"SCROLLError","t":"trait SCROLLError extends Throwable","d":"scroll/internal/errors/SCROLLErrors$$SCROLLError","k":"trait"},
{"l":"scroll/internal/errors/SCROLLErrors$$TypeError.html","n":"TypeError","t":"trait TypeError extends Throwable","d":"scroll/internal/errors/SCROLLErrors$$TypeError","k":"trait"},
{"l":"scroll/internal/errors/SCROLLErrors$$TypeNotFound.html","n":"TypeNotFound","t":"class TypeNotFound(tpe: Class[_]) extends TypeError","d":"scroll/internal/errors/SCROLLErrors$$TypeNotFound","k":"class"},
{"l":"scroll/internal/formal.html","n":"scroll.internal.formal","t":"package scroll.internal.formal","d":"scroll/internal/formal","k":"package"},
{"l":"scroll/internal/formal/CROI.html","n":"CROI","t":"trait CROI extends CROM","d":"scroll/internal/formal/CROI","k":"trait"},
{"l":"scroll/internal/formal/CROI.html","n":"addCompartment","t":"def addCompartment[T <: AnyRef : ClassTag](c: T): Unit","d":"scroll/internal/formal/CROI","k":"def"},
{"l":"scroll/internal/formal/CROI.html","n":"addNatural","t":"def addNatural(n: AnyRef): Unit","d":"scroll/internal/formal/CROI","k":"def"},
{"l":"scroll/internal/formal/CROI.html","n":"addPlays","t":"def addPlays(player: AnyRef, comp: AnyRef, role: AnyRef): Unit","d":"scroll/internal/formal/CROI","k":"def"},
{"l":"scroll/internal/formal/CROI.html","n":"addRole","t":"def addRole(r: AnyRef): Unit","d":"scroll/internal/formal/CROI","k":"def"},
{"l":"scroll/internal/formal/CROI.html","n":"compliant","t":"def compliant(path: String): Boolean","d":"scroll/internal/formal/CROI","k":"def"},
{"l":"scroll/internal/formal/CROI.html","n":"croi","t":"val croi: FormalCROI[String, String, String, String]","d":"scroll/internal/formal/CROI","k":"val"},
{"l":"scroll/internal/formal/CROM.html","n":"CROM","t":"trait CROM extends ECoreImporter","d":"scroll/internal/formal/CROM","k":"trait"},
{"l":"scroll/internal/formal/CROM.html","n":"wellformed","t":"def wellformed(path: String): Boolean","d":"scroll/internal/formal/CROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROI$.html","n":"FormalCROI","t":"object FormalCROI","d":"scroll/internal/formal/FormalCROI$","k":"object"},
{"l":"scroll/internal/formal/FormalCROI$.html","n":"empty","t":"def empty[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef]: FormalCROI[NT, RT, CT, RST]","d":"scroll/internal/formal/FormalCROI$","k":"def"},
{"l":"scroll/internal/formal/FormalCROI$.html","n":"forStrings","t":"def forStrings(n: List[String], r: List[String], c: List[String], type1: Map[AnyRef, AnyRef], plays: List[(String, String, String)], links: Map[(String, String), List[(String, String)]]): FormalCROI[String, String, String, String]","d":"scroll/internal/formal/FormalCROI$","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"FormalCROI","t":"class FormalCROI[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef](var n: List[NT], var r: List[RT], var c: List[CT], var type1: Map[AnyRef, AnyRef], var plays: List[(NT, CT, RT)], var links: Map[(RST, CT), List[(RT, RT)]])","d":"scroll/internal/formal/FormalCROI","k":"class"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom10","t":"def axiom10(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom11","t":"def axiom11(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom6","t":"def axiom6(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom7","t":"def axiom7(): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom8","t":"def axiom8(): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"axiom9","t":"def axiom9(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"compliant","t":"def compliant(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"o_c","t":"def o_c(c: CT): List[NT]","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"overline_links","t":"def overline_links(rst: RST, c: CT): List[(NT, NT)]","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"pred","t":"def pred(rst: RST, c: CT, r: RT): List[RT]","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROI.html","n":"succ","t":"def succ(rst: RST, c: CT, r: RT): List[RT]","d":"scroll/internal/formal/FormalCROI","k":"def"},
{"l":"scroll/internal/formal/FormalCROM$.html","n":"FormalCROM","t":"object FormalCROM","d":"scroll/internal/formal/FormalCROM$","k":"object"},
{"l":"scroll/internal/formal/FormalCROM$.html","n":"empty","t":"def empty[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef]: FormalCROM[NT, RT, CT, RST]","d":"scroll/internal/formal/FormalCROM$","k":"def"},
{"l":"scroll/internal/formal/FormalCROM$.html","n":"forStrings","t":"def forStrings(nt: List[String], rt: List[String], ct: List[String], rst: List[String], fills: List[(String, String)], parts: Map[String, List[String]], rel: Map[String, List[String]]): FormalCROM[String, String, String, String]","d":"scroll/internal/formal/FormalCROM$","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"FormalCROM","t":"class FormalCROM[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef](nt: List[NT], rt: List[RT], ct: List[CT], rst: List[RST], fills: List[(NT, RT)], parts: Map[CT, List[RT]], rel: Map[RST, List[RT]])","d":"scroll/internal/formal/FormalCROM","k":"class"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"axiom1","t":"def axiom1: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"axiom2","t":"def axiom2: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"axiom3","t":"def axiom3: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"axiom4","t":"def axiom4: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"axiom5","t":"def axiom5: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalCROM.html","n":"wellformed","t":"def wellformed: Boolean","d":"scroll/internal/formal/FormalCROM","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel$.html","n":"FormalConstraintModel","t":"object FormalConstraintModel","d":"scroll/internal/formal/FormalConstraintModel$","k":"object"},
{"l":"scroll/internal/formal/FormalConstraintModel$.html","n":"empty","t":"def empty[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef]: FormalConstraintModel[NT, RT, CT, RST]","d":"scroll/internal/formal/FormalConstraintModel$","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel$.html","n":"forStrings","t":"def forStrings(rolec: Map[String, List[((Int, Int), AnyRef)]], card: Map[String, ((Int, Int), (Int, Int))], intra: List[(String, List[(String, String)] => Boolean)]): FormalConstraintModel[String, String, String, String]","d":"scroll/internal/formal/FormalConstraintModel$","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"FormalConstraintModel","t":"class FormalConstraintModel[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef](rolec: Map[CT, List[((Int, Int), AnyRef)]], card: Map[RST, ((Int, Int), (Int, Int))], intra: List[(RST, List[(NT, NT)] => Boolean)])","d":"scroll/internal/formal/FormalConstraintModel","k":"class"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"axiom12","t":"def axiom12(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"axiom13","t":"def axiom13(crom: FormalCROM[NT, RT, CT, RST], croi: FormalCROI[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"axiom14","t":"def axiom14(croi: FormalCROI[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"axiom15","t":"def axiom15(crom: FormalCROM[NT, RT, CT, RST], croi: FormalCROI[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"axiom16","t":"def axiom16(croi: FormalCROI[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"compliant","t":"def compliant(crom: FormalCROM[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalConstraintModel.html","n":"validity","t":"def validity(crom: FormalCROM[NT, RT, CT, RST], croi: FormalCROI[NT, RT, CT, RST]): Boolean","d":"scroll/internal/formal/FormalConstraintModel","k":"def"},
{"l":"scroll/internal/formal/FormalRoleGroup.html","n":"FormalRoleGroup","t":"class FormalRoleGroup(rolegroups: List[AnyRef], lower: Int, upper: Int)","d":"scroll/internal/formal/FormalRoleGroup","k":"class"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"FormalUtils","t":"object FormalUtils","d":"scroll/internal/formal/FormalUtils$","k":"object"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"all","t":"def all(on: List[Boolean]): Boolean","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"any","t":"def any(on: List[Boolean]): Boolean","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"atoms","t":"def atoms[T >: Null <: AnyRef](a: AnyRef): List[T]","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"evaluate","t":"def evaluate[NT >: Null <: AnyRef, RT >: Null <: AnyRef, CT >: Null <: AnyRef, RST >: Null <: AnyRef](a: AnyRef, croi: FormalCROI[NT, RT, CT, RST], o: NT, c: CT): Int","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"mutualDisjoint","t":"def mutualDisjoint[T](sets: List[List[T]]): Boolean","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/formal/FormalUtils$.html","n":"totalFunction","t":"def totalFunction[T, RT](domain: List[T], foo: Map[T, List[RT]]): Boolean","d":"scroll/internal/formal/FormalUtils$","k":"def"},
{"l":"scroll/internal/graph.html","n":"scroll.internal.graph","t":"package scroll.internal.graph","d":"scroll/internal/graph","k":"package"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"RoleGraph","t":"trait RoleGraph","d":"scroll/internal/graph/RoleGraph","k":"trait"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"addBinding","t":"def addBinding(player: AnyRef, role: AnyRef): Unit","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"addPart","t":"def addPart(other: RoleGraph): Boolean","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"allPlayers","t":"def allPlayers: Seq[AnyRef]","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"containsPlayer","t":"def containsPlayer(player: AnyRef): Boolean","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"coreFor","t":"def coreFor(role: AnyRef): Seq[AnyRef]","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"detach","t":"def detach(other: RoleGraph): Unit","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"facets","t":"def facets(player: AnyRef): Seq[Value]","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"predecessors","t":"def predecessors(player: AnyRef): Seq[AnyRef]","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"removeBinding","t":"def removeBinding(player: AnyRef, role: AnyRef): Unit","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"removePlayer","t":"def removePlayer(player: AnyRef): Unit","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraph.html","n":"roles","t":"def roles(player: AnyRef): Seq[AnyRef]","d":"scroll/internal/graph/RoleGraph","k":"def"},
{"l":"scroll/internal/graph/RoleGraphProxyApi.html","n":"RoleGraphProxyApi","t":"trait RoleGraphProxyApi","d":"scroll/internal/graph/RoleGraphProxyApi","k":"trait"},
{"l":"scroll/internal/graph/RoleGraphProxyApi.html","n":"reconfigure","t":"def reconfigure(cached: Boolean, checkForCycles: Boolean): Unit","d":"scroll/internal/graph/RoleGraphProxyApi","k":"def"},
{"l":"scroll/internal/graph/impl.html","n":"scroll.internal.graph.impl","t":"package scroll.internal.graph.impl","d":"scroll/internal/graph/impl","k":"package"},
{"l":"scroll/internal/graph/impl/CachedScalaRoleGraph$.html","n":"CachedScalaRoleGraph","t":"object CachedScalaRoleGraph","d":"scroll/internal/graph/impl/CachedScalaRoleGraph$","k":"object"},
{"l":"scroll/internal/graph/impl/CachedScalaRoleGraph$.html","n":"copyFrom","t":"def copyFrom(from: ScalaRoleGraph, checkForCycles: Boolean): CachedScalaRoleGraph","d":"scroll/internal/graph/impl/CachedScalaRoleGraph$","k":"def"},
{"l":"scroll/internal/graph/impl/CachedScalaRoleGraph.html","n":"CachedScalaRoleGraph","t":"class CachedScalaRoleGraph(root: MutableGraph[Object], checkForCycles: Boolean) extends ScalaRoleGraph","d":"scroll/internal/graph/impl/CachedScalaRoleGraph","k":"class"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraph$.html","n":"ScalaRoleGraph","t":"object ScalaRoleGraph","d":"scroll/internal/graph/impl/ScalaRoleGraph$","k":"object"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraph$.html","n":"copyFrom","t":"def copyFrom(from: ScalaRoleGraph, checkForCycles: Boolean): ScalaRoleGraph","d":"scroll/internal/graph/impl/ScalaRoleGraph$","k":"def"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraph.html","n":"ScalaRoleGraph","t":"class ScalaRoleGraph(val root: MutableGraph[Object], val checkForCycles: Boolean) extends RoleGraph","d":"scroll/internal/graph/impl/ScalaRoleGraph","k":"class"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraph.html","n":"checkForCycles","t":"val checkForCycles: Boolean","d":"scroll/internal/graph/impl/ScalaRoleGraph","k":"val"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraph.html","n":"root","t":"val root: MutableGraph[Object]","d":"scroll/internal/graph/impl/ScalaRoleGraph","k":"val"},
{"l":"scroll/internal/graph/impl/ScalaRoleGraphProxy.html","n":"ScalaRoleGraphProxy","t":"class ScalaRoleGraphProxy extends RoleGraphProxyApi","d":"scroll/internal/graph/impl/ScalaRoleGraphProxy","k":"class"},
{"l":"scroll/internal/rpa.html","n":"scroll.internal.rpa","t":"package scroll.internal.rpa","d":"scroll/internal/rpa","k":"package"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$.html","n":"RolePlayingAutomaton","t":"object RolePlayingAutomaton","d":"scroll/internal/rpa/RolePlayingAutomaton$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$.html","n":"Use","t":"def Use[T <: AnyRef : ClassTag]: RPABuilder[T]","d":"scroll/internal/rpa/RolePlayingAutomaton$","k":"def"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$BindRole$.html","n":"BindRole","t":"object BindRole extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$BindRole$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$CheckConstraints$.html","n":"CheckConstraints","t":"object CheckConstraints extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$CheckConstraints$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$RPAData.html","n":"RPAData","t":"trait RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$RPAData","k":"trait"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$RPAState.html","n":"RPAState","t":"trait RPAState","d":"scroll/internal/rpa/RolePlayingAutomaton$$RPAState","k":"trait"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$RemoveRole$.html","n":"RemoveRole","t":"object RemoveRole extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$RemoveRole$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$Start$.html","n":"Start","t":"object Start extends RPAState","d":"scroll/internal/rpa/RolePlayingAutomaton$$Start$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$Stop$.html","n":"Stop","t":"object Stop extends RPAState","d":"scroll/internal/rpa/RolePlayingAutomaton$$Stop$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$Terminate$.html","n":"Terminate","t":"object Terminate extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$Terminate$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$TransferRole$.html","n":"TransferRole","t":"object TransferRole extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$TransferRole$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton$$Uninitialized$.html","n":"Uninitialized","t":"object Uninitialized extends RPAData","d":"scroll/internal/rpa/RolePlayingAutomaton$$Uninitialized$","k":"object"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton.html","n":"RolePlayingAutomaton","t":"trait RolePlayingAutomaton extends Actor with LoggingFSM[RPAState, RPAData]","d":"scroll/internal/rpa/RolePlayingAutomaton","k":"trait"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton.html","n":"halt","t":"def halt(): State","d":"scroll/internal/rpa/RolePlayingAutomaton","k":"def"},
{"l":"scroll/internal/rpa/RolePlayingAutomaton.html","n":"run","t":"def run(): Unit","d":"scroll/internal/rpa/RolePlayingAutomaton","k":"def"},
{"l":"scroll/internal/support.html","n":"scroll.internal.support","t":"package scroll.internal.support","d":"scroll/internal/support","k":"package"},
{"l":"scroll/internal/support/CompartmentRelationsApi.html","n":"CompartmentRelationsApi","t":"trait CompartmentRelationsApi","d":"scroll/internal/support/CompartmentRelationsApi","k":"trait"},
{"l":"scroll/internal/support/CompartmentRelationsApi.html","n":"combine","t":"def combine(other: CompartmentApi): Unit","d":"scroll/internal/support/CompartmentRelationsApi","k":"def"},
{"l":"scroll/internal/support/CompartmentRelationsApi.html","n":"notPartOf","t":"def notPartOf(other: CompartmentApi): Unit","d":"scroll/internal/support/CompartmentRelationsApi","k":"def"},
{"l":"scroll/internal/support/CompartmentRelationsApi.html","n":"partOf","t":"def partOf(other: CompartmentApi): Unit","d":"scroll/internal/support/CompartmentRelationsApi","k":"def"},
{"l":"scroll/internal/support/CompartmentRelationsApi.html","n":"union","t":"def union(other: CompartmentApi): Unit","d":"scroll/internal/support/CompartmentRelationsApi","k":"def"},
{"l":"scroll/internal/support/PlayerEqualityApi.html","n":"PlayerEqualityApi","t":"trait PlayerEqualityApi","d":"scroll/internal/support/PlayerEqualityApi","k":"trait"},
{"l":"scroll/internal/support/PlayerEqualityApi.html","n":"equalsAny","t":"def equalsAny[W <: AnyRef : ClassTag](a: IPlayer[W, _], b: AnyRef): Boolean","d":"scroll/internal/support/PlayerEqualityApi","k":"def"},
{"l":"scroll/internal/support/PlayerEqualityApi.html","n":"equalsPlayer","t":"def equalsPlayer[W <: AnyRef : ClassTag](a: IPlayer[W, _], b: IPlayer[W, _]): Boolean","d":"scroll/internal/support/PlayerEqualityApi","k":"def"},
{"l":"scroll/internal/support/RelationshipsApi.html","n":"RelationshipsApi","t":"trait RelationshipsApi","d":"scroll/internal/support/RelationshipsApi","k":"trait"},
{"l":"scroll/internal/support/RelationshipsApi.html","n":"create","t":"def create(name: String): FromBuilderApi","d":"scroll/internal/support/RelationshipsApi","k":"def"},
{"l":"scroll/internal/support/RelationshipsApi$FromBuilderApi.html","n":"FromBuilderApi","t":"class FromBuilderApi","d":"scroll/internal/support/RelationshipsApi$FromBuilderApi","k":"class"},
{"l":"scroll/internal/support/RelationshipsApi$FromBuilderApi.html","n":"from","t":"def from[L <: AnyRef : ClassTag](leftMul: Multiplicity): ToBuilderApi[L]","d":"scroll/internal/support/RelationshipsApi$FromBuilderApi","k":"def"},
{"l":"scroll/internal/support/RelationshipsApi$RelationshipApi.html","n":"RelationshipApi","t":"class RelationshipApi[L <: AnyRef, R <: AnyRef]","d":"scroll/internal/support/RelationshipsApi$RelationshipApi","k":"class"},
{"l":"scroll/internal/support/RelationshipsApi$RelationshipApi.html","n":"left","t":"def left(matcher: L => Boolean): Seq[L]","d":"scroll/internal/support/RelationshipsApi$RelationshipApi","k":"def"},
{"l":"scroll/internal/support/RelationshipsApi$RelationshipApi.html","n":"right","t":"def right(matcher: R => Boolean): Seq[R]","d":"scroll/internal/support/RelationshipsApi$RelationshipApi","k":"def"},
{"l":"scroll/internal/support/RelationshipsApi$ToBuilderApi.html","n":"ToBuilderApi","t":"class ToBuilderApi[L <: AnyRef]","d":"scroll/internal/support/RelationshipsApi$ToBuilderApi","k":"class"},
{"l":"scroll/internal/support/RelationshipsApi$ToBuilderApi.html","n":"to","t":"def to[R <: AnyRef : ClassTag](rightMul: Multiplicity): RelationshipApi[L, R]","d":"scroll/internal/support/RelationshipsApi$ToBuilderApi","k":"def"},
{"l":"scroll/internal/support/RoleConstraintsApi.html","n":"RoleConstraintsApi","t":"trait RoleConstraintsApi","d":"scroll/internal/support/RoleConstraintsApi","k":"trait"},
{"l":"scroll/internal/support/RoleConstraintsApi.html","n":"addRoleEquivalence","t":"def addRoleEquivalence[A <: AnyRef : ClassTag, B <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleConstraintsApi","k":"def"},
{"l":"scroll/internal/support/RoleConstraintsApi.html","n":"addRoleImplication","t":"def addRoleImplication[A <: AnyRef : ClassTag, B <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleConstraintsApi","k":"def"},
{"l":"scroll/internal/support/RoleConstraintsApi.html","n":"addRoleProhibition","t":"def addRoleProhibition[A <: AnyRef : ClassTag, B <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleConstraintsApi","k":"def"},
{"l":"scroll/internal/support/RoleConstraintsApi.html","n":"checked","t":"def checked(func: => Unit): Unit","d":"scroll/internal/support/RoleConstraintsApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi.html","n":"RoleGroupsApi","t":"trait RoleGroupsApi","d":"scroll/internal/support/RoleGroupsApi","k":"trait"},
{"l":"scroll/internal/support/RoleGroupsApi.html","n":"checked","t":"def checked(func: => Unit): Unit","d":"scroll/internal/support/RoleGroupsApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi.html","n":"create","t":"def create(name: String): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"RoleGroupApi","t":"trait RoleGroupApi extends Entry","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"trait"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing(rg: RoleGroupApi*)(limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing[T1 <: AnyRef : ClassTag](limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing[T1 <: AnyRef : ClassTag, T2 <: AnyRef : ClassTag](limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing[T1 <: AnyRef : ClassTag, T2 <: AnyRef : ClassTag, T3 <: AnyRef : ClassTag](limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing[T1 <: AnyRef : ClassTag, T2 <: AnyRef : ClassTag, T3 <: AnyRef : ClassTag, T4 <: AnyRef : ClassTag](limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RoleGroupsApi$RoleGroupApi.html","n":"containing","t":"def containing[T1 <: AnyRef : ClassTag, T2 <: AnyRef : ClassTag, T3 <: AnyRef : ClassTag, T4 <: AnyRef : ClassTag, T5 <: AnyRef : ClassTag](limitLower: Int, limitUpper: CInt)(occLower: Int, occUpper: CInt): RoleGroupApi","d":"scroll/internal/support/RoleGroupsApi$RoleGroupApi","k":"def"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"RolePlayingApi","t":"trait RolePlayingApi","d":"scroll/internal/support/RolePlayingApi","k":"trait"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"addPlaysRelation","t":"def addPlaysRelation[C <: AnyRef : ClassTag, R <: AnyRef : ClassTag](core: C, role: R): Unit","d":"scroll/internal/support/RolePlayingApi","k":"def"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"allPlayers","t":"def allPlayers: Seq[AnyRef]","d":"scroll/internal/support/RolePlayingApi","k":"def"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"removePlayer","t":"def removePlayer(player: AnyRef): Unit","d":"scroll/internal/support/RolePlayingApi","k":"def"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"removePlaysRelation","t":"def removePlaysRelation(core: AnyRef, role: AnyRef): Unit","d":"scroll/internal/support/RolePlayingApi","k":"def"},
{"l":"scroll/internal/support/RolePlayingApi.html","n":"transferRole","t":"def transferRole[F <: AnyRef : ClassTag, T <: AnyRef : ClassTag, R <: AnyRef : ClassTag](coreFrom: F, coreTo: T, role: R): Unit","d":"scroll/internal/support/RolePlayingApi","k":"def"},
{"l":"scroll/internal/support/RoleQueriesApi.html","n":"RoleQueriesApi","t":"trait RoleQueriesApi","d":"scroll/internal/support/RoleQueriesApi","k":"trait"},
{"l":"scroll/internal/support/RoleQueriesApi.html","n":"all","t":"def all[T <: AnyRef : ClassTag](matcher: RoleQueryStrategy): Seq[T]","d":"scroll/internal/support/RoleQueriesApi","k":"def"},
{"l":"scroll/internal/support/RoleQueriesApi.html","n":"all","t":"def all[T <: AnyRef : ClassTag](matcher: T => Boolean): Seq[T]","d":"scroll/internal/support/RoleQueriesApi","k":"def"},
{"l":"scroll/internal/support/RoleQueriesApi.html","n":"one","t":"def one[T <: AnyRef : ClassTag](matcher: RoleQueryStrategy): Either[TypeError, T]","d":"scroll/internal/support/RoleQueriesApi","k":"def"},
{"l":"scroll/internal/support/RoleQueriesApi.html","n":"one","t":"def one[T <: AnyRef : ClassTag](matcher: T => Boolean): Either[TypeError, T]","d":"scroll/internal/support/RoleQueriesApi","k":"def"},
{"l":"scroll/internal/support/RoleRestrictionsApi.html","n":"RoleRestrictionsApi","t":"trait RoleRestrictionsApi","d":"scroll/internal/support/RoleRestrictionsApi","k":"trait"},
{"l":"scroll/internal/support/RoleRestrictionsApi.html","n":"addRoleRestriction","t":"def addRoleRestriction[A <: AnyRef : ClassTag, B <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleRestrictionsApi","k":"def"},
{"l":"scroll/internal/support/RoleRestrictionsApi.html","n":"removeRoleRestriction","t":"def removeRoleRestriction[A <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleRestrictionsApi","k":"def"},
{"l":"scroll/internal/support/RoleRestrictionsApi.html","n":"replaceRoleRestriction","t":"def replaceRoleRestriction[A <: AnyRef : ClassTag, B <: AnyRef : ClassTag](): Unit","d":"scroll/internal/support/RoleRestrictionsApi","k":"def"},
{"l":"scroll/internal/support/RoleRestrictionsApi.html","n":"validate","t":"def validate[R <: AnyRef : ClassTag](player: AnyRef, role: R): Unit","d":"scroll/internal/support/RoleRestrictionsApi","k":"def"},
{"l":"scroll/internal/support/impl.html","n":"scroll.internal.support.impl","t":"package scroll.internal.support.impl","d":"scroll/internal/support/impl","k":"package"},
{"l":"scroll/internal/support/impl/CompartmentRelations.html","n":"CompartmentRelations","t":"class CompartmentRelations(roleGraph: RoleGraphProxyApi) extends CompartmentRelationsApi","d":"scroll/internal/support/impl/CompartmentRelations","k":"class"},
{"l":"scroll/internal/support/impl/Multiplicities$.html","n":"Multiplicities","t":"object Multiplicities","d":"scroll/internal/support/impl/Multiplicities$","k":"object"},
{"l":"scroll/internal/support/impl/Multiplicities$.html","n":"intToConcreteValue","t":"def intToConcreteValue(v: Int): ConcreteValue","d":"scroll/internal/support/impl/Multiplicities$","k":"def"},
{"l":"scroll/internal/support/impl/Multiplicities$.html","n":"orderedToConcreteValue","t":"def orderedToConcreteValue(v: Ordered[Int]): ExpMultiplicity","d":"scroll/internal/support/impl/Multiplicities$","k":"def"},
{"l":"scroll/internal/support/impl/Multiplicities$$ConcreteValue.html","n":"ConcreteValue","t":"class ConcreteValue(v: Ordered[Int]) extends ExpMultiplicity","d":"scroll/internal/support/impl/Multiplicities$$ConcreteValue","k":"class"},
{"l":"scroll/internal/support/impl/Multiplicities$$ConcreteValue.html","n":"To","t":"def To(t: ExpMultiplicity): Multiplicity","d":"scroll/internal/support/impl/Multiplicities$$ConcreteValue","k":"def"},
{"l":"scroll/internal/support/impl/Multiplicities$$ExpMultiplicity.html","n":"ExpMultiplicity","t":"trait ExpMultiplicity extends Multiplicity","d":"scroll/internal/support/impl/Multiplicities$$ExpMultiplicity","k":"trait"},
{"l":"scroll/internal/support/impl/Multiplicities$$MMany.html","n":"MMany","t":"class MMany() extends ExpMultiplicity","d":"scroll/internal/support/impl/Multiplicities$$MMany","k":"class"},
{"l":"scroll/internal/support/impl/Multiplicities$$Multiplicity.html","n":"Multiplicity","t":"trait Multiplicity","d":"scroll/internal/support/impl/Multiplicities$$Multiplicity","k":"trait"},
{"l":"scroll/internal/support/impl/Multiplicities$$RangeMultiplicity.html","n":"RangeMultiplicity","t":"class RangeMultiplicity(from: ExpMultiplicity, to: ExpMultiplicity) extends Multiplicity","d":"scroll/internal/support/impl/Multiplicities$$RangeMultiplicity","k":"class"},
{"l":"scroll/internal/support/impl/PlayerEquality.html","n":"PlayerEquality","t":"class PlayerEquality(roleGraph: RoleGraphProxyApi) extends PlayerEqualityApi","d":"scroll/internal/support/impl/PlayerEquality","k":"class"},
{"l":"scroll/internal/support/impl/QueryStrategies$.html","n":"QueryStrategies","t":"object QueryStrategies","d":"scroll/internal/support/impl/QueryStrategies$","k":"object"},
{"l":"scroll/internal/support/impl/QueryStrategies$$MatchAny.html","n":"MatchAny","t":"class MatchAny() extends RoleQueryStrategy","d":"scroll/internal/support/impl/QueryStrategies$$MatchAny","k":"class"},
{"l":"scroll/internal/support/impl/QueryStrategies$$RoleQueryStrategy.html","n":"RoleQueryStrategy","t":"class RoleQueryStrategy","d":"scroll/internal/support/impl/QueryStrategies$$RoleQueryStrategy","k":"class"},
{"l":"scroll/internal/support/impl/QueryStrategies$$RoleQueryStrategy.html","n":"matches","t":"def matches(on: AnyRef): Boolean","d":"scroll/internal/support/impl/QueryStrategies$$RoleQueryStrategy","k":"def"},
{"l":"scroll/internal/support/impl/QueryStrategies$$WithProperty.html","n":"WithProperty","t":"class WithProperty[T](name: String, value: T) extends RoleQueryStrategy","d":"scroll/internal/support/impl/QueryStrategies$$WithProperty","k":"class"},
{"l":"scroll/internal/support/impl/QueryStrategies$$WithResult.html","n":"WithResult","t":"class WithResult[T](name: String, result: T) extends RoleQueryStrategy","d":"scroll/internal/support/impl/QueryStrategies$$WithResult","k":"class"},
{"l":"scroll/internal/support/impl/Relationships.html","n":"Relationships","t":"class Relationships(roleQueries: RoleQueriesApi) extends RelationshipsApi","d":"scroll/internal/support/impl/Relationships","k":"class"},
{"l":"scroll/internal/support/impl/Relationships$FromBuilder.html","n":"FromBuilder","t":"class FromBuilder(name: String) extends FromBuilderApi","d":"scroll/internal/support/impl/Relationships$FromBuilder","k":"class"},
{"l":"scroll/internal/support/impl/Relationships$Relationship.html","n":"Relationship","t":"class Relationship[L <: AnyRef, R <: AnyRef](name: String, leftMul: Multiplicity, rightMul: Multiplicity)(implicit evidence$2: ClassTag[L], evidence$3: ClassTag[R]) extends RelationshipApi[L, R]","d":"scroll/internal/support/impl/Relationships$Relationship","k":"class"},
{"l":"scroll/internal/support/impl/Relationships$ToBuilder.html","n":"ToBuilder","t":"class ToBuilder[L <: AnyRef](name: String, leftMul: Multiplicity)(implicit evidence$1: ClassTag[L]) extends ToBuilderApi[L]","d":"scroll/internal/support/impl/Relationships$ToBuilder","k":"class"},
{"l":"scroll/internal/support/impl/RoleConstraints.html","n":"RoleConstraints","t":"class RoleConstraints(roleGraph: RoleGraphProxyApi) extends RoleConstraintsApi","d":"scroll/internal/support/impl/RoleConstraints","k":"class"},
{"l":"scroll/internal/support/impl/RoleGroups.html","n":"RoleGroups","t":"class RoleGroups(roleGraph: RoleGraphProxyApi) extends RoleGroupsApi","d":"scroll/internal/support/impl/RoleGroups","k":"class"},
{"l":"scroll/internal/support/impl/RoleGroups$RoleGroup.html","n":"RoleGroup","t":"class RoleGroup(name: String, entries: Seq[Entry], limit: (Int, CInt), occ: (Int, CInt), var evaluated: Boolean) extends RoleGroupApi","d":"scroll/internal/support/impl/RoleGroups$RoleGroup","k":"class"},
{"l":"scroll/internal/support/impl/RolePlaying.html","n":"RolePlaying","t":"class RolePlaying(roleGraph: RoleGraphProxyApi, roleRestrictions: RoleRestrictionsApi) extends RolePlayingApi","d":"scroll/internal/support/impl/RolePlaying","k":"class"},
{"l":"scroll/internal/support/impl/RoleQueries.html","n":"RoleQueries","t":"class RoleQueries(roleGraph: RoleGraphProxyApi) extends RoleQueriesApi","d":"scroll/internal/support/impl/RoleQueries","k":"class"},
{"l":"scroll/internal/support/impl/RoleRestrictions.html","n":"RoleRestrictions","t":"class RoleRestrictions() extends RoleRestrictionsApi","d":"scroll/internal/support/impl/RoleRestrictions","k":"class"},
{"l":"scroll/internal/util.html","n":"scroll.internal.util","t":"package scroll.internal.util","d":"scroll/internal/util","k":"package"},
{"l":"scroll/internal/util/Many$.html","n":"Many","t":"object Many","d":"scroll/internal/util/Many$","k":"object"},
{"l":"scroll/internal/util/Many$.html","n":"*","t":"def *: Many","d":"scroll/internal/util/Many$","k":"def"},
{"l":"scroll/internal/util/Many.html","n":"Many","t":"class Many() extends Ordered[Int]","d":"scroll/internal/util/Many","k":"class"},
{"l":"scroll/internal/util/Memoiser$.html","n":"Memoiser","t":"object Memoiser","d":"scroll/internal/util/Memoiser$","k":"object"},
{"l":"scroll/internal/util/Memoiser$.html","n":"buildCache","t":"def buildCache[K <: AnyRef, V <: AnyRef](supplier: K => V): LoadingCache[K, V]","d":"scroll/internal/util/Memoiser$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"ReflectiveHelper","t":"object ReflectiveHelper","d":"scroll/internal/util/ReflectiveHelper$","k":"object"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"addToFieldCache","t":"def addToFieldCache(c: Class[_]): Unit","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"addToMethodCache","t":"def addToMethodCache(c: Class[_]): Unit","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"findMethod","t":"def findMethod(on: AnyRef, name: String, args: Seq[Any]): Option[Method]","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"hasMember","t":"def hasMember(on: AnyRef, name: String): Boolean","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"is","t":"def is[T <: AnyRef : ClassTag](on: AnyRef): Boolean","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"isInstanceOf","t":"def isInstanceOf(mani: String, that: AnyRef): Boolean","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"isInstanceOf","t":"def isInstanceOf(mani: String, that: String): Boolean","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"isSameInterface","t":"def isSameInterface(roleInterface: Array[Method], restrInterface: Array[Method]): Boolean","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"propertyOf","t":"def propertyOf[T](on: AnyRef, name: String): T","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"resultOf","t":"def resultOf[T](on: AnyRef, m: Method, args: Seq[Any]): T","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"resultOf","t":"def resultOf[T](on: AnyRef, name: String): T","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"setPropertyOf","t":"def setPropertyOf(on: AnyRef, name: String, value: Any): Unit","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"scroll/internal/util/ReflectiveHelper$.html","n":"simpleName","t":"def simpleName(t: String): String","d":"scroll/internal/util/ReflectiveHelper$","k":"def"},
{"l":"docs/index.html","n":"SCROLL","t":"SCROLL","d":"","k":"static"}];