name: pr
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - name: Set up SBT
        uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - name: Check formatting
        run: sbt "scalafmtCheckAll; scalafmtSbtCheck;"
      - run: echo "Previous step failed because code is not formatted. Run 'sbt format'"
        if: ${{ failure() }}

  test-scroll:
    needs: format
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - name: Set up SBT
        uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - name: Compile and run tests
        run: sbt "test"

  jmh-compile:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - name: Set up SBT
        uses: sbt/setup-sbt@ce95da69b39609ea153bad087708da5f37366897 # v1.5.10
      - name: Compile JMH benchmarks
        run: sbt "benchmark/Jmh/compile"
